### ISSUE TITLE
Alt Modifier Remapping Behavior

### ISSUE THREAD

**Issue by MrX101** [dodekeract/manta-config-engine-app#30] opened 2016-02-13 19:53 UTC
There seems to be no way to bind the following:

"Alt Modifier Key"
"Open Chat"  (incase u wanted it to be a different key than enter)

**Comment by FlorianWendelborn** [comment] 2016-02-13 19:54
Alt Modifier is true, I forgot to port it to the new keybinding changer.
Open Chat can be found under Open -> Open Chat

**Comment by FlorianWendelborn** [comment] 2016-02-13 20:22
Should be live now.

**Comment by MrX101** [comment] 2016-02-13 20:24
Uhh it seems bugged, if you set a key to the alt modifier, u can no longer change it to anything else unless you set the alt modifier to something else first.

**Comment by FlorianWendelborn** [comment] 2016-02-13 20:35
What would you suggest Manta should do? Reset it to Alt when you attempt to re-bind it to something else? Right now, it's working as intended, although I see why this behavior might be confusing.

Tell me if you have any suggestion what Manta should do instead.

**Comment by MrX101** [comment] 2016-02-13 20:41
Ahh I understand now, because it needs to have a key set to the alt modifier.
Just make it do a popup to inform the user.

"Alt modifier must always be binded to a key"
"Please set the alt modifier to a different key instead"

**Comment by FlorianWendelborn** [comment] 2016-02-13 20:43
Yeah, alt-modifier is a special case, which is why I missed it while updating the keybind changer. Will probably implement that popup warning later.

**Comment by MrX101** [comment] 2016-02-13 21:00
ohh and jump to recent event is missing in the camera section
although u can do it via bind command section. however its saved in the following manner

bind "SPACE" "dota_recent_event undefined"
instead of
bind "SPACE" "dota_recent_event"

dota_recent_event

**Comment by FlorianWendelborn** [comment] 2016-02-13 21:33
That undefined bug should be fixed now.

**Comment by FlorianWendelborn** [comment] 2016-02-19 13:12
A warning message is now implemented as of 25ab4f0ba826764d23476b8c2ee0380d6b9a0d48.

**Closed as completed by FlorianWendelborn** 2016-02-19 13:12 UTC
Labels: enhancement
