### ISSUE TITLE
Why does your config use unbindall at the start of each layout?

### ISSUE THREAD

**Issue by AlexWFreitas** [dodekeract/manta-config-engine-app#42] opened 2016-02-15 20:41 UTC
It removes everything you set up through Dota. So you need to set up everything through those autoexecs.

I only need this script for selfcast, not for anything else, also it is missing the hotkeys to gather items from stash.

**Comment by AlexWFreitas** [comment] 2016-02-15 20:43
Plus you can't use alt modifier hotkeys. So you are required to do it ingame, but because of `unbindall` you will never have alt hotkeys.

**Comment by Sembrani** [comment] 2016-02-16 00:55
There is no need for obscenities.
unbindall is used to facilitate multiple layers in the config. If you want to use alt-modifiers, create an extra layer in the app bound to Alt. I can't comment on the lack of hotkey for gathering items from stash however. It is probably an oversight.

**Comment by FlorianWendelborn** [comment] 2016-02-16 07:05
I guess I could implement an option to disable `unbindall`. Didn't think it would unbind things set in the UI. Since it does I can see how this would be useful.

**Comment by FlorianWendelborn** [comment] 2016-02-16 07:06
Until that option is live, just work-around it by deleting that line.

**Comment by FlorianWendelborn** [comment] 2016-02-16 07:39
So. I thought about this issue and I think I found a quite good solution. Just removing `unbindall` will lead to some unexpected behaviour, since you can use keys from Layout1 in Layout2, unless you have overwritten them.

Since Manta is computer-generated, I should be able to change `unbindall` to a solution, which only unbinds keys you set in Manta.

**Comment by AlexWFreitas** [comment] 2016-02-16 18:57
Yeah, that would be better, sorry for the obscenities, I was really mad because I set everything correctly on Steam and on Manta Engine, so I went to play and all my binds disappeared when I pressed space. So it was making a huge nightmare for me.

**Comment by AlexWFreitas** [comment] 2016-02-16 18:58
Since I only set hotkeys for quickcasting and self casting, I was without hotkeys to attack, control groups, tabbing, selecting courier, pausing, chatting, everything didn't work.

**Comment by FlorianWendelborn** [comment] 2016-02-16 19:15
That's why you should always test it out in a private lobby first. :smile:

**Comment by AlexWFreitas** [comment] 2016-02-16 19:16
The thing is I tested, I even made the binds on Steam on the previous day after I saw they weren't working. But then it unbinds it again at the start.

**Comment by FlorianWendelborn** [comment] 2016-03-28 18:12
@otaru1921 That should be fixed now. Manta now tries to only `unbind` keys, which it actually uses. Let me know if you still see anything wrong with how it works.

**Closed as completed by FlorianWendelborn** 2016-03-28 18:12 UTC
Labels: enhancement, question
